version: '3.8'
services:
  orchestrator:
    build: .
    image: ai-media-pipeline
    container_name: ai-media-orchestrator
    volumes:
      - ./ai_media_pipeline/samples:/app/ai_media_pipeline/samples
      - ./ai_media_pipeline/outputs:/app/ai_media_pipeline/outputs
    working_dir: /app
    entrypoint: ["python3", "-m", "ai_media_pipeline.orchestrator.app"]
    # Example command (override as needed)
    command: ["--file", "ai_media_pipeline/samples/input.wav", "--output", "ai_media_pipeline/outputs/input.json"]

  api:
    build: .
    image: ai-media-pipeline
    container_name: ai-media-api
    ports:
      - "8000:8000"
    volumes:
      - ./ai_media_pipeline/samples:/app/ai_media_pipeline/samples
      - ./ai_media_pipeline/outputs:/app/ai_media_pipeline/outputs
    working_dir: /app
    entrypoint: ["python3", "-m", "ai_media_pipeline.orchestrator.app", "serve"]
    command: []

# To run the CLI batch job:
#   docker-compose run orchestrator --file ... --output ...
# To run the API and web UI:
#   docker-compose up api 
